import { Injectable, Logger } from '@nestjs/common';
import { v4 as uuidv4 } from 'uuid';
import { StrategyOrchestratorService } from '../strategy/strategy-orchestrator.service';
import { AuditService } from '../audit/audit.service';
import { DomainEventBus } from '../events/event-bus.service';
import { DomainEventType } from '../events/enums/domain-event-type.enum';
import { AuditAction } from '../../common/enums/audit-action.enum';
import { AuditSeverity } from '../audit/entities/audit-log.entity';
import { AiSignalCandidate } from './interfaces/ai-signal-candidate.interface';
import { StrategyResult } from '../strategy/interfaces/strategy.interface';

/**
 * AiSignalService — Safe signal intake service for the AI Signal Engine.
 *
 * This service is the NestJS entry point for signals generated by Python
 * AI microservices (or DEV simulation). It validates, logs, and forwards
 * signals to the Strategy Orchestrator.
 *
 * CRITICAL INVARIANT:
 *   Signals are NEVER sent directly to ExecutionService or BrokerAdapter.
 *   All signals must pass through StrategyOrchestratorService.
 *
 * Pipeline:
 *   receiveSignal() → validateCandidate() → forwardToStrategyOrchestrator()
 *                  → StrategyOrchestratorService.processSignal()
 *                  → RiskService → ExecutionService → Broker
 *
 * See: docs/architecture/10-ai-trading-architecture.md
 */
@Injectable()
export class AiSignalService {
  private readonly logger = new Logger(AiSignalService.name);

  constructor(
    private readonly strategyOrchestrator: StrategyOrchestratorService,
    private readonly auditService: AuditService,
    private readonly eventBus: DomainEventBus,
  ) {}

  /**
   * Primary entry point. Validates and forwards to Strategy Orchestrator.
   */
  async receiveSignal(candidate: AiSignalCandidate): Promise<StrategyResult> {
    this.logger.log(
      `Signal received: id=${candidate.signalId} user=${candidate.userId} ` +
      `instrument=${candidate.instrument} direction=${candidate.direction}`,
    );

    const validationError = this.validateCandidate(candidate);
    if (validationError) {
      this.logger.warn(`Signal ${candidate.signalId} validation failed: ${validationError}`);
      await this.auditService.log({
        actorUserId: candidate.userId,
        action: AuditAction.AI_SIGNAL_RECEIVED,
        severity: AuditSeverity.INFO,
        resourceType: 'AiSignal',
        resourceId: candidate.signalId,
        metadata: { validationError, instrument: candidate.instrument, direction: candidate.direction },
      });
      return {
        outcome: 'SIGNAL_INVALID',
        signalId: candidate.signalId,
        reason: validationError,
      };
    }

    await this.auditService.log({
      actorUserId: candidate.userId,
      action: AuditAction.AI_SIGNAL_RECEIVED,
      severity: AuditSeverity.INFO,
      resourceType: 'AiSignal',
      resourceId: candidate.signalId,
      metadata: {
        instrument: candidate.instrument,
        direction: candidate.direction,
        confidenceScore: candidate.confidenceScore,
        strategyCode: candidate.strategyCode,
        modelVersion: candidate.modelVersion,
      },
    });

    this.eventBus.publish(DomainEventType.AI_SIGNAL_RECEIVED, candidate.userId, {
      signalId: candidate.signalId,
      instrument: candidate.instrument,
      direction: candidate.direction,
      confidenceScore: candidate.confidenceScore,
      strategyCode: candidate.strategyCode,
    });

    return this.forwardToStrategyOrchestrator(candidate);
  }

  /**
   * Validate the structural integrity of a signal candidate.
   * Returns null if valid, or an error message string.
   */
  validateCandidate(candidate: AiSignalCandidate): string | null {
    if (!candidate.signalId) return 'Missing signalId';
    if (!candidate.userId) return 'Missing userId';
    if (!candidate.tradingSessionId) return 'Missing tradingSessionId';
    if (!candidate.brokerConnectionId) return 'Missing brokerConnectionId';
    if (!candidate.instrument || candidate.instrument.length < 3) return 'Invalid instrument';
    if (!['BUY', 'SELL'].includes(candidate.direction)) return 'Invalid direction';
    if (typeof candidate.confidenceScore !== 'number' || candidate.confidenceScore < 0 || candidate.confidenceScore > 1) {
      return 'confidenceScore must be 0–1';
    }
    if (!candidate.suggestedStopLoss || candidate.suggestedStopLoss <= 0) return 'Invalid suggestedStopLoss';
    if (!candidate.suggestedTakeProfit || candidate.suggestedTakeProfit <= 0) return 'Invalid suggestedTakeProfit';
    if (!candidate.suggestedVolume || candidate.suggestedVolume <= 0) return 'Invalid suggestedVolume';
    if (!candidate.strategyCode) return 'Missing strategyCode';
    if (!candidate.modelVersion) return 'Missing modelVersion';
    return null;
  }

  /**
   * Forward a validated candidate to the Strategy Orchestrator.
   * Do NOT call ExecutionService directly from here.
   */
  async forwardToStrategyOrchestrator(candidate: AiSignalCandidate): Promise<StrategyResult> {
    return this.strategyOrchestrator.processSignal(candidate);
  }

  /**
   * Build a signal candidate from the DEV simulate endpoint request.
   * Assigns a new signalId and generatedAt timestamp.
   */
  buildSimulatedCandidate(
    userId: string,
    dto: Partial<AiSignalCandidate>,
  ): AiSignalCandidate {
    return {
      signalId: uuidv4(),
      generatedAt: new Date(),
      ...dto,
      userId,
    } as AiSignalCandidate;
  }
}
