import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Normalize legacy UUID defaults from `uuid_generate_v4()` to `gen_random_uuid()`.
 *
 * Context
 * -------
 * Three tables created by earlier migrations use `uuid_generate_v4()` (from
 * the uuid-ossp extension) as the `DEFAULT` for their UUID primary key:
 *
 *   1. broker_reconciliation.broker_trade_reconciliation_runs.id
 *      (migration 1751200000000)
 *   2. broker_reconciliation.broker_reconciled_trades.id
 *      (migration 1751200000000)
 *   3. performance_billing.performance_fee_billing_cycles.id
 *      (migration 1751300000000)
 *
 * The baseline migration (1750800000000) intentionally standardizes on
 * `gen_random_uuid()` (pgcrypto / core PG 13+) and explicitly avoids
 * `uuid_generate_v4()` to prevent staging failures where
 * `public.uuid_generate_v4()` already exists as a standalone function.
 *
 * This migration normalizes the three outlier tables to match the baseline
 * convention, so the database no longer depends on the uuid-ossp extension
 * (or the compatibility bridge from migration 1751150000000) for new-row UUID
 * generation.
 *
 * Safety
 * ------
 * - ALTERs ONLY the `DEFAULT` expression of the three `id` columns.
 * - Does NOT regenerate IDs.
 * - Does NOT modify existing rows or UUID values.
 * - Does NOT modify primary keys, foreign keys, column types, or financial data.
 * - Existing UUID values (generated by either function historically) remain
 *   untouched — a UUID is a UUID regardless of which function produced it.
 *
 * Reversibility
 * -------------
 * `down()` restores the previous `uuid_generate_v4()` default ONLY when it is
 * safe to do so — i.e. when the function is guaranteed to be available at
 * that point in the migration-revert sequence. Because the bridge migration
 * (1751150000000) runs before the table-creating migrations, reverting this
 * normalization migration first (while the bridge is still present) is safe.
 * If the bridge has already been reverted, `down()` checks function
 * availability before restoring the default and skips (with a warning) if the
 * function is absent, rather than leaving the table in a broken state.
 *
 * Ordering
 * --------
 * Timestamp 1752200000000 — runs AFTER all existing migrations (the latest
 * prior is 1752100000000), so all three target tables already exist.
 */
export class NormalizeLegacyUuidDefaults1752200000000 implements MigrationInterface {
  name = 'NormalizeLegacyUuidDefaults1752200000000';

  /**
   * The three legacy default expressions to normalize. Each entry maps a
   * qualified table+column to its old and new default.
   */
  private readonly targets: ReadonlyArray<{
    schema: string;
    table: string;
    column: string;
  }> = [
    {
      schema: 'broker_reconciliation',
      table: 'broker_trade_reconciliation_runs',
      column: 'id',
    },
    {
      schema: 'broker_reconciliation',
      table: 'broker_reconciled_trades',
      column: 'id',
    },
    {
      schema: 'performance_billing',
      table: 'performance_fee_billing_cycles',
      column: 'id',
    },
  ];

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const t of this.targets) {
      // Guard: only ALTER if the table exists (idempotent on partial DBs).
      const tableExists = await queryRunner.query(
        `SELECT to_regclass('${t.schema}.${t.table}') IS NOT NULL AS exists`,
      );
      const exists = tableExists?.[0]?.exists === true || tableExists?.[0]?.exists === 't';
      if (!exists) continue;

      // Guard: only ALTER if the current default actually uses
      // uuid_generate_v4(). This makes the migration idempotent and avoids
      // touching tables that were already normalized.
      const currentDefault = await queryRunner.query(`
        SELECT pg_get_expr(adbin, adrelid) AS default_expr
        FROM pg_attrdef
        WHERE adrelid = '${t.schema}.${t.table}'::regclass
          AND adnum = (
            SELECT attnum FROM pg_attribute
            WHERE attrelid = '${t.schema}.${t.table}'::regclass
              AND attname = '${t.column}'
          )
      `);
      const defaultExpr = currentDefault?.[0]?.default_expr ?? '';
      if (!defaultExpr.includes('uuid_generate_v4')) {
        // Already normalized (or no default). Skip.
        continue;
      }

      // ALTER the column default. Do NOT touch the column type, NOT NULL,
      // or any existing data. The USING clause is omitted intentionally —
      // ALTER COLUMN ... SET DEFAULT does not rewrite rows.
      await queryRunner.query(`
        ALTER TABLE ${t.schema}.${t.table}
          ALTER COLUMN ${t.column} SET DEFAULT gen_random_uuid()
      `);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    // Only restore the uuid_generate_v4() default if the function is
    // available at this point in the revert sequence. The bridge migration
    // (1751150000000) is reverted AFTER this migration (reverse chronological
    // order: 1752200000000 down() runs before 1751150000000 down()), so the
    // bridge function should still exist. But verify to be safe.
    const funcAvailable = await queryRunner.query(`
      SELECT EXISTS (
        SELECT 1 FROM pg_proc p
        JOIN pg_namespace n ON n.oid = p.pronamespace
        WHERE n.nspname = 'public' AND p.proname = 'uuid_generate_v4'
          AND p.pronargs = 0
      ) AS exists
    `);
    const funcExists = funcAvailable?.[0]?.exists === true || funcAvailable?.[0]?.exists === 't';
    if (!funcExists) {
      // Function not available — restoring the old default would leave the
      // table in a broken state (INSERT without explicit id would fail).
      // Skip the restore rather than creating a broken default. Log via
      // queryRunner for operator visibility.
      console.warn(
        'NormalizeLegacyUuidDefaults down(): public.uuid_generate_v4() is not available; ' +
          'skipping default restore to avoid leaving tables in a broken state. ' +
          'The columns retain gen_random_uuid() default.',
      );
      return;
    }

    for (const t of this.targets) {
      const tableExists = await queryRunner.query(
        `SELECT to_regclass('${t.schema}.${t.table}') IS NOT NULL AS exists`,
      );
      const exists = tableExists?.[0]?.exists === true || tableExists?.[0]?.exists === 't';
      if (!exists) continue;

      await queryRunner.query(`
        ALTER TABLE ${t.schema}.${t.table}
          ALTER COLUMN ${t.column} SET DEFAULT uuid_generate_v4()
      `);
    }
  }
}
