export enum AuditAction {
  // Auth
  USER_REGISTERED = 'USER_REGISTERED',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED = 'USER_LOGIN_FAILED',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_TOKEN_REFRESHED = 'USER_TOKEN_REFRESHED',
  USER_PASSWORD_RESET_REQUESTED = 'USER_PASSWORD_RESET_REQUESTED',
  USER_PASSWORD_RESET_COMPLETED = 'USER_PASSWORD_RESET_COMPLETED',
  USER_EMAIL_VERIFIED = 'USER_EMAIL_VERIFIED',
  USER_MFA_ENABLED = 'USER_MFA_ENABLED',
  USER_MFA_DISABLED = 'USER_MFA_DISABLED',

  // Users
  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_REACTIVATED = 'USER_REACTIVATED',
  USER_CLOSED = 'USER_CLOSED',
  RISK_DISCLOSURE_ACCEPTED = 'RISK_DISCLOSURE_ACCEPTED',

  // Subscriptions
  SUBSCRIPTION_CREATED = 'SUBSCRIPTION_CREATED',
  SUBSCRIPTION_ACTIVATED = 'SUBSCRIPTION_ACTIVATED',
  SUBSCRIPTION_CANCELLED = 'SUBSCRIPTION_CANCELLED',
  SUBSCRIPTION_EXPIRED = 'SUBSCRIPTION_EXPIRED',
  SUBSCRIPTION_MANUAL_ACTIVATED = 'SUBSCRIPTION_MANUAL_ACTIVATED',

  // Admin
  ADMIN_ACTION = 'ADMIN_ACTION',
  ADMIN_USER_VIEWED = 'ADMIN_USER_VIEWED',
  COUNTRY_CONFIG_UPDATED = 'COUNTRY_CONFIG_UPDATED',

  // Broker connections
  BROKER_CONNECTION_CREATED = 'BROKER_CONNECTION_CREATED',
  BROKER_CONNECTION_UPDATED = 'BROKER_CONNECTION_UPDATED',
  BROKER_CONNECTION_DELETED = 'BROKER_CONNECTION_DELETED',
  BROKER_CONNECTION_TESTED = 'BROKER_CONNECTION_TESTED',
  BROKER_CONNECTION_TEST_FAILED = 'BROKER_CONNECTION_TEST_FAILED',
  BROKER_CONNECTED = 'BROKER_CONNECTED',
  BROKER_CONNECT_FAILED = 'BROKER_CONNECT_FAILED',
  BROKER_DISCONNECTED = 'BROKER_DISCONNECTED',
  BROKER_SUSPENDED_HEALTH_FAILURE = 'BROKER_SUSPENDED_HEALTH_FAILURE',
  BROKER_CREDENTIAL_ENCRYPTION_FAILED = 'BROKER_CREDENTIAL_ENCRYPTION_FAILED',
  BROKER_LIVE_TRADING_ENABLED = 'BROKER_LIVE_TRADING_ENABLED',
  BROKER_LIVE_TRADING_DISABLED = 'BROKER_LIVE_TRADING_DISABLED',

  // Risk Engine
  RISK_KILL_SWITCH_ACTIVATED = 'RISK_KILL_SWITCH_ACTIVATED',
  RISK_KILL_SWITCH_DEACTIVATED = 'RISK_KILL_SWITCH_DEACTIVATED',
  RISK_PROFILE_UPDATED = 'RISK_PROFILE_UPDATED',
  RISK_PROFILE_CREATED = 'RISK_PROFILE_CREATED',
  RISK_POSITION_SIZE_REDUCED = 'RISK_POSITION_SIZE_REDUCED',
  RISK_DAILY_LOSS_LIMIT_BREACHED = 'RISK_DAILY_LOSS_LIMIT_BREACHED',
  RISK_DRAWDOWN_LIMIT_BREACHED = 'RISK_DRAWDOWN_LIMIT_BREACHED',
  RISK_SESSION_SUSPENDED = 'RISK_SESSION_SUSPENDED',

  // Trade execution lifecycle
  TRADE_PREPARED = 'TRADE_PREPARED',
  TRADE_SUBMITTED = 'TRADE_SUBMITTED',
  TRADE_OPENED = 'TRADE_OPENED',
  TRADE_MODIFIED = 'TRADE_MODIFIED',
  TRADE_CLOSED = 'TRADE_CLOSED',
  TRADE_REJECTED = 'TRADE_REJECTED',
  TRADE_RECONCILED = 'TRADE_RECONCILED',

  // AI trading session
  AI_TRADING_ENABLED = 'AI_TRADING_ENABLED',
  AI_TRADING_DISABLED = 'AI_TRADING_DISABLED',

  // Market data (internal)
  MARKET_DATA_REQUESTED = 'MARKET_DATA_REQUESTED',
  MARKET_DATA_REQUEST_FAILED = 'MARKET_DATA_REQUEST_FAILED',

  // AI signal lifecycle
  AI_SIGNAL_RECEIVED = 'AI_SIGNAL_RECEIVED',
  AI_SIGNAL_RISK_REJECTED = 'AI_SIGNAL_RISK_REJECTED',
  AI_SIGNAL_EXECUTED = 'AI_SIGNAL_EXECUTED',
  AI_SIGNAL_EXECUTION_FAILED = 'AI_SIGNAL_EXECUTION_FAILED',

  // Payment lifecycle
  PAYMENT_CHECKOUT_INITIATED = 'PAYMENT_CHECKOUT_INITIATED',
  PAYMENT_CHECKOUT_FAILED = 'PAYMENT_CHECKOUT_FAILED',
  // Sprint 16 — subscription checkout idempotency / pending invoice reuse
  PAYMENT_CHECKOUT_REUSED = 'PAYMENT_CHECKOUT_REUSED',
  PAYMENT_CHECKOUT_PROVIDER_SESSION_REUSED = 'PAYMENT_CHECKOUT_PROVIDER_SESSION_REUSED',
  PAYMENT_WEBHOOK_RECEIVED = 'PAYMENT_WEBHOOK_RECEIVED',
  PAYMENT_WEBHOOK_SIGNATURE_FAILED = 'PAYMENT_WEBHOOK_SIGNATURE_FAILED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  // Invoice lifecycle
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_PAID = 'INVOICE_PAID',

  // Performance fee lifecycle
  PERFORMANCE_FEE_POLICY_CREATED = 'PERFORMANCE_FEE_POLICY_CREATED',
  PERFORMANCE_FEE_ASSESSMENT_CALCULATED = 'PERFORMANCE_FEE_ASSESSMENT_CALCULATED',
  PERFORMANCE_FEE_ASSESSMENT_INVOICED = 'PERFORMANCE_FEE_ASSESSMENT_INVOICED',
  PERFORMANCE_FEE_ASSESSMENT_WAIVED = 'PERFORMANCE_FEE_ASSESSMENT_WAIVED',
  PERFORMANCE_FEE_PAID = 'PERFORMANCE_FEE_PAID',
  PERFORMANCE_FEE_LEDGER_ENTRY_CREATED = 'PERFORMANCE_FEE_LEDGER_ENTRY_CREATED',
  HIGH_WATER_MARK_UPDATED = 'HIGH_WATER_MARK_UPDATED',

  // Performance fee invoice payment flow (Sprint 14)
  PERFORMANCE_FEE_CHECKOUT_INITIATED = 'PERFORMANCE_FEE_CHECKOUT_INITIATED',
  PERFORMANCE_FEE_CHECKOUT_FAILED = 'PERFORMANCE_FEE_CHECKOUT_FAILED',
  PERFORMANCE_FEE_PAYMENT_STATUS_VIEWED = 'PERFORMANCE_FEE_PAYMENT_STATUS_VIEWED',

  // Broker trade reconciliation
  BROKER_RECONCILIATION_STARTED = 'BROKER_RECONCILIATION_STARTED',
  BROKER_RECONCILIATION_COMPLETED = 'BROKER_RECONCILIATION_COMPLETED',
  BROKER_RECONCILIATION_FAILED = 'BROKER_RECONCILIATION_FAILED',
  BROKER_TRADE_RECONCILED = 'BROKER_TRADE_RECONCILED',
  BROKER_TRADE_RECONCILIATION_SKIPPED = 'BROKER_TRADE_RECONCILIATION_SKIPPED',
  PERFORMANCE_FEE_LEDGER_ENTRY_CREATED_FROM_BROKER_TRADE = 'PERFORMANCE_FEE_LEDGER_ENTRY_CREATED_FROM_BROKER_TRADE',

  // Performance fee billing cycle
  PERFORMANCE_BILLING_CYCLE_CREATED = 'PERFORMANCE_BILLING_CYCLE_CREATED',
  PERFORMANCE_BILLING_CYCLE_STARTED = 'PERFORMANCE_BILLING_CYCLE_STARTED',
  PERFORMANCE_BILLING_CYCLE_RECONCILED = 'PERFORMANCE_BILLING_CYCLE_RECONCILED',
  PERFORMANCE_BILLING_CYCLE_ASSESSED = 'PERFORMANCE_BILLING_CYCLE_ASSESSED',
  PERFORMANCE_BILLING_CYCLE_INVOICED = 'PERFORMANCE_BILLING_CYCLE_INVOICED',
  PERFORMANCE_BILLING_CYCLE_NO_FEE_DUE = 'PERFORMANCE_BILLING_CYCLE_NO_FEE_DUE',
  PERFORMANCE_BILLING_CYCLE_FAILED = 'PERFORMANCE_BILLING_CYCLE_FAILED',
  PERFORMANCE_BILLING_CYCLE_CANCELLED = 'PERFORMANCE_BILLING_CYCLE_CANCELLED',

}
