import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';

export enum LedgerEntryType {
  /** External capital added — EXCLUDED from realised profit calculation */
  DEPOSIT = 'DEPOSIT',
  /** External capital removed — factored into net calculation */
  WITHDRAWAL = 'WITHDRAWAL',
  /** Closed winning trade P&L — counted in realised profit basis */
  REALISED_TRADE_PROFIT = 'REALISED_TRADE_PROFIT',
  /** Closed losing trade P&L — reduces realised profit basis */
  REALISED_TRADE_LOSS = 'REALISED_TRADE_LOSS',
  /** Performance fee assessed (assessment record created) */
  FEE_ASSESSED = 'FEE_ASSESSED',
  /** Performance fee paid (invoice settled) */
  FEE_PAID = 'FEE_PAID',
  /** Manual correction entry by admin */
  ADJUSTMENT = 'ADJUSTMENT',
}

/**
 * PerformanceFeeLedgerEntry
 *
 * Immutable event log for all performance-fee-relevant monetary movements
 * for a user's trading account.
 *
 * IMPORTANT:
 * - Only REALISED_TRADE_PROFIT and REALISED_TRADE_LOSS entries count toward fee basis.
 * - DEPOSIT entries are EXCLUDED from profit calculation.
 * - Entries for demo, paper, or backtest trades must NEVER be added.
 * - Amounts are in minor currency units (bigint strings).
 * - Ledger entries are append-only; no updates after creation.
 */
@Entity({ name: 'performance_fee_ledger_entries', schema: 'performance_fees' })
@Index(['userId'])
@Index(['userId', 'brokerConnectionId'])
@Index(['occurredAt'])
@Index(['userId', 'occurredAt'])
export class PerformanceFeeLedgerEntry {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ name: 'user_id', type: 'uuid' })
  @Index()
  userId: string;

  /** Linked assessment if this entry was generated by a fee assessment */
  @Column({ name: 'assessment_id', type: 'uuid', nullable: true })
  @Index()
  assessmentId: string | null;

  @Column({ name: 'broker_connection_id', type: 'uuid', nullable: true })
  @Index()
  brokerConnectionId: string | null;

  @Column({ name: 'entry_type', type: 'enum', enum: LedgerEntryType })
  entryType: LedgerEntryType;

  @Column({ name: 'currency', type: 'varchar', length: 3 })
  currency: string;

  /** Amount in minor currency units. Losses are stored as negative values. */
  @Column({ name: 'amount', type: 'bigint' })
  amount: string;

  /** External reference (e.g. trade ID, transaction ID) */
  @Column({ name: 'source_reference', type: 'varchar', length: 255, nullable: true })
  sourceReference: string | null;

  @Column({ name: 'occurred_at', type: 'timestamptz' })
  occurredAt: Date;

  /** Safe metadata — must not contain secrets, credentials, or raw provider payloads */
  @Column({ name: 'metadata', type: 'jsonb', nullable: true })
  metadata: Record<string, unknown> | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;
}
